### 카프카 프로듀싱 API 테스트
POST localhost:8081/v1/kafka/message
Content-Type: application/json

{
  "name": "진카미",
  "age": 32
}

### 카프카 구매정보 프로듀싱 API 테스트
POST localhost:8081/v1/kafka/purchase
Content-Type: application/json

{
  "first_name": "lim",
  "last_name": "ho",
  "customer_id": "syn1341",
  "credit_card_number": "0200-1243-4321-7777",
  "item_purchased": "iphone15 Pro",
  "department": "electronics",
  "employee_id": "paysec",
  "quantity": 1,
  "price": 1210000,
  "purchase_date": "20231014",
  "zip_code": "정자동 75-8",
  "store_id": "paysec-3"
}


### 카프카 구매정보 프로듀싱 API 테스트
POST localhost:8081/v1/kafka/purchase
Content-Type: application/json

{
  "first_name": "lim",
  "last_name": "ho",
  "customer_id": "syn1341",
  "credit_card_number": "0200-1243-4321-7777",
  "item_purchased": "HOT Americano",
  "department": "coffee",
  "employee_id": "paysec",
  "quantity": 1,
  "price": 3300,
  "purchase_date": "20231014",
  "zip_code": "정자동 75-8",
  "store_id": "paysec-3"
}

### 카프카 주식정보 프로듀싱 API 테스트
POST localhost:8081/v1/kafka/stock
Content-Type: application/json

{
  "price": 110000,
  "symbol": "kakaopay"
}

### websocket
WEBSOCKET ws://localhost:8081/chat
X-I-AM: a